### ISSUE TITLE
undefined method `version_scheme'

### ISSUE THREAD

**Issue by gaoyifan** [gaoyifan/homebrew-bottle-mirror#2]
```
Error: undefined method `version_scheme' for #<Class:0x007fc9c60c9300>
/root/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/pyenv.rb:6:in `<class:Pyenv>'
/root/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/pyenv.rb:1:in `load_formula'
/root/.linuxbrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/root/.linuxbrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/root/.linuxbrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/root/.linuxbrew/Library/Homebrew/formulary.rb:91:in `load_file'
/root/.linuxbrew/Library/Homebrew/formulary.rb:82:in `klass'
/root/.linuxbrew/Library/Homebrew/formulary.rb:78:in `get_formula'
/root/.linuxbrew/Library/Homebrew/formulary.rb:215:in `factory'
/root/.linuxbrew/Library/Homebrew/formula.rb:1202:in `[]'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:4:in `block in <top (required)>'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:3:in `each'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:3:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/root/.linuxbrew/Library/Homebrew/brew.rb:22:in `require?'
/root/.linuxbrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by gaoyifan** [comment]
fixed https://github.com/gaoyifan/homebrew-bottle-mirror/commit/d0fb6766acf1b247a04484cd18d79c77608f946c
