### ISSUE TITLE
同步脚本失效

### ISSUE THREAD

**Issue by z4yx** [gaoyifan/homebrew-bottle-mirror#6]
最近可能上游修改了fomula格式，现在同步脚本不work了，tuna服务器的日志摘录如下（每个包都会打印类似的错误）：
```
Warning: /home/homebrew/.linuxbrew/homebrew/Library/Taps/homebrew/homebrew-core/Formula/sdns.rb: something goes wrong.
Warning: /home/homebrew/.linuxbrew/homebrew/Library/Taps/homebrew/homebrew-core/Formula/iproute2mac.rb: something goes wrong.
Warning: /home/homebrew/.linuxbrew/homebrew/Library/Taps/homebrew/homebrew-core/Formula/grin.rb: something goes wrong.
Warning: /home/homebrew/.linuxbrew/homebrew/Library/Taps/homebrew/homebrew-core/Formula/bitcoin.rb: something goes wrong.
Warning: /home/homebrew/.linuxbrew/homebrew/Library/Taps/homebrew/homebrew-core/Formula/chapel.rb: something goes wrong.
Warning: /home/homebrew/.linuxbrew/homebrew/Library/Taps/homebrew/homebrew-core/Formula/dfc.rb: something goes wrong.
Warning: /home/homebrew/.linuxbrew/homebrew/Library/Taps/homebrew/homebrew-core/Formula/faiss.rb: something goes wrong.
Warning: /home/homebrew/.linuxbrew/homebrew/Library/Taps/homebrew/homebrew-core/Formula/xlearn.rb: something goes wrong.
sdns: undefined method `license' for Formulary::FormulaNamespaceba328642f7a35b88d61745bb38d1b354::Sdns:Class
["/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:36:in `rescue in load_formula'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:33:in `load_formula'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:54:in `load_formula_from_path'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:136:in `load_file'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:126:in `klass'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:122:in `get_formula'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:331:in `factory'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formula.rb:1482:in `[]'", "/home/homebrew/.linuxbrew/homebrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:101:in `block (2 levels) in <top (required)>'", "/home/homebrew/.linuxbrew/homebrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:13:in `block in initialize'"]
root_url: https://homebrew.bintray.com/bottles, filename: libre-0.6.1.catalina.bottle.tar.gz
iproute2mac: uninitialized constant Language::Python::Shebang
["/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:36:in `rescue in load_formula'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:33:in `load_formula'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:54:in `load_formula_from_path'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:136:in `load_file'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:126:in `klass'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:122:in `get_formula'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:331:in `factory'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formula.rb:1482:in `[]'", "/home/homebrew/.linuxbrew/homebrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:101:in `block (2 levels) in <top (required)>'", "/home/homebrew/.linuxbrew/homebrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:13:in `block in initialize'"]
grin: undefined method `license' for Formulary::FormulaNamespace3c461c5652df5df4fe4bedd4293baf8a::Grin:Class
["/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:36:in `rescue in load_formula'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:33:in `load_formula'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:54:in `load_formula_from_path'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:136:in `load_file'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:126:in `klass'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:122:in `get_formula'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formulary.rb:331:in `factory'", "/home/homebrew/.linuxbrew/homebrew/Library/Homebrew/formula.rb:1482:in `[]'", "/home/homebrew/.linuxbrew/homebrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:101:in `block (2 levels) in <top (required)>'", "/home/homebrew/.linuxbrew/homebrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:13:in `block in initialize'"]
bitcoin: undefined method `license' for #<Class:0x0000557e6782efe8>
```

不知道ustc站是否遇到。大佬有什么修改思路吗？

**Comment by taoky** [comment]
似乎现在的同步脚本无法正确处理包含 license 字段的 formula？不包含这个字段的包（例如 i2util）同步是正常的。

**Comment by taoky** [comment]
我修改了科大镜像站使用的 homebrew-bottles image（<https://github.com/ustclug/ustcmirror-images/commit/9b24016a60b990512c0896a1aed3df8b7818337f>），并且目前看来同步没有出问题（同步还在跑）。

修改方法是：
1. 使用 Alpine 3.11 构建镜像（因为 3.11 有 Ruby 2.6.x，更新的 Alpine 版本的 Ruby 就是 2.7+ 了，而 Homebrew 需要 2.6.x 的 Ruby。在我们的 image 上测试 homebrew 安装自己的 portable ruby 会失败。）
2. `apk` 安装依赖加上 `ruby-fiddle`。

如果这个仓库要改的话，smartentry/alpine 可能要加上 3.11 这个版本？（并且需要每隔一段时间就构建一次 image？）

**Comment by gaoyifan** [comment]
已修复，本地测试正常

@taoky 感谢提供修复思路 
@z4yx  感谢报告故障

**Comment by gaoyifan** [comment]
@taoky
FYI,  smartentry 每周会自动构建一次新版本 (travis-ci cron job)

**Comment by skyzh** [comment]
感觉可以考虑使用官方 API 获取 bottles 地址，而非扫描 formula？

FYI: https://formulae.brew.sh/docs/api/

FYI: https://github.com/sjtug/mirror-clone/blob/master/src/homebrew.rs

**Comment by gaoyifan** [comment]
@skyzh  非常棒的主意～ 近期来试试看

**Comment by gaoyifan** [comment]
尝试写了一个基于JSON API 的同步脚本，效果很好～
https://github.com/ustclug/ustcmirror-images/blob/master/homebrew-bottles/sync.sh

这种方式应该能规避几乎所有的 brew ruby API 变动导致的同步工具失效问题
如果没有其他意外，ruby 版本的同步程序将不再维护

@skyzh  非常感谢提供思路和参考方案！
