### ISSUE TITLE
Homebrew/brew 的 master 最新 commit 中 Checksum 对象不再包含 hash_type 方法

### ISSUE THREAD

**Issue by taoky** [gaoyifan/homebrew-bottle-mirror#9]
https://github.com/Homebrew/brew/commit/5e91802470c23963c573db660c25bd915f57183e#diff-b3c658d990062dd092574fada51d693426f29891928462e2a24379e81800671c

这导致了运行到 https://github.com/gaoyifan/homebrew-bottle-mirror/blob/master/cmd/brew-bottle-mirror.rb#L119 时执行出错：

```
Error: undefined method `hash_type' for #<Checksum:0x0000564df4695f58>
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:28:in `block (2 levels) in <top (required)>'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:21:in `each'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:21:in `block in <top (required)>'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:8:in `each'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:8:in `<top (required)>'
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/root/.linuxbrew/Library/Homebrew/utils.rb:92:in `require?'
/root/.linuxbrew/Library/Homebrew/brew.rb:126:in `<main>'
```

似乎把这一行删掉就行了？

**Comment by gaoyifan** [comment]
是的～ 按说删掉 hash_type 的判断即可，我今天测试一下
